import type {
  CrewCardData, AbilityGroup, ActionGroup, TriggerGroup, TriggerActionType,
  Ability, Action, ActionType, Trigger,
  Marker, Token, TerrainFeature,
} from '../../types'
import { FACTIONS } from '../../factions'
import { AbilityEntry, ActionEntry, TriggerEntry, GroupHeader } from '../../SharedComponents/FormComponents'
import '../../SharedComponents/FormComponents/FormStyles.css'

const TOKEN_PRESETS: Record<string, string> = {
  'Abandoned': "During the end phase, if this model does not have more models (other than itself) it considers friendly within 3\" of it than models it considers enemy, this model is dealt 2 irreducible damage. Then, if this token did not damage this model, remove this token.",
  'Adaptable': "Before performing a duel, this model may remove this token to add a suit of its choice to its duel total.",
  'Adversary': "Friendly models receive a + to attack actions targeting this model. During the end phase, remove this token.",
  'Aetheric Surge': "This model receives +2 Skl and a suit of its choice when declaring attack actions.",
  'Analyzed': "This model may not reduce damage with its abilities. Remove this token during the end phase.",
  'Aura (Binding)': "Enemy models within 6\" may not empower duels. During the end phase, remove this token.",
  'Aura (Concealment)': "The area within 2\" of this model is concealing terrain. Friendly models may choose to be unaffected by this terrain. During the end phase, remove this token.",
  'Aura (Fire)': "The area within 2\" of this model is hazardous (Burning) terrain. Friendly models may choose to be unaffected by this terrain. During the end phase, remove this token.",
  'Aura (Fumes)': "Enemy models within 3\" receive a - to attack actions that target friendly models. During the end phase, remove this token.",
  'Aura (Hazardous)': "The area within 2\" of this model is hazardous terrain. Friendly models may choose to be unaffected by this terrain. During the end phase, remove this token.",
  'Aura (Negligent)': "Enemy models within 2\" of this model that declare a non-Walk action must pass a TN 10 Wp duel or the action fails. During the end phase, remove this token.",
  'Aura (Poison)': "The area within 2\" of this model is hazardous (Poison) terrain. Friendly models may choose to be unaffected by this terrain. During the end phase, remove this token.",
  'Aura (Staggered)': "When an enemy model within 2\" of this model activates, it must discard a card or gain a Staggered token.",
  'Backtrack': "When performing a duel, this model may remove this token before any player cheats fate. If it does so, all cards in the conflict are discarded without effect and the duel is performed again with the same modifiers. This token may not be used if there are any jokers in the conflict.",
  'Badge': "When this model would be killed, it may discard a card and remove this token to heal 2.",
  'Balm': "During the end phase, this model heals 1. Then, remove this token.",
  'Blight': "This model suffers a - to Wp duels generated by Plague models. During the end phase, enemy models within 1\" gain a Blight token, then if there are no other models within 1\" with a Blight token, remove this token.",
  'Bog Spirit': "After this model is killed, the crew that applied this token may summon a Will o' the Wisp with 3 health into base contact.",
  'Bolstered': "This model receives +1 to its Df and Wp. During the end phase, remove this token. Canceled by Injured.",
  'Brilliance': "When this model cheats fate, the crew that applied this token may remove it to deal 1 damage to this model or heal it 2.",
  'Broodling': "After this model is killed, summon a friendly Terror Tot into base contact.",
  'Burning': "During the end phase deal 1 damage to this model and enemy models in base contact with it. Then remove this token.",
  'Challenged': "This model must discard a card to target any model other than the one that applied this token. During the end phase, remove this token.",
  'Chi': "Before performing a duel, this model may remove this token to receive +1 to its duel total.",
  'Convert': "The Dmg stat of this model's attack actions is reduced by 1.",
  'Craven': "This model cannot declare the Interact action and is ignored for strategies and schemes. When this model ends its activation, remove this token.",
  'Death': "When this model succeeds in an attack action that deals damage, it may remove this token. If it does so, the target must either discard a card, drain a 💎, or be killed.",
  'Distracted': "When this model targets a friendly model, it must remove this token and suffer a - to that action's duel. Canceled by Focused.",
  'Drift': "When this model activates, it may remove this token to place into base contact with a friendly Tide marker within 5\".",
  'Entranced': "This model's actions that target a friendly model cannot be cheated. After this model resolves an action targeting a friendly model, remove this token.",
  'Explosive': "A model with an Explosive token may take the Interact action to remove the token and make a friendly Strategy marker within 1\", and not within 4\" of another friendly Strategy marker. Explosive tokens may not be removed in any other way.",
  'Exposed': "This model cannot gain cover. During the end phase, remove this token. Canceled by Hidden.",
  'Familia': "When a friendly model within 6\" is dealt damage, this model may remove this token to reduce that damage by 1.",
  'Fast': "Increase this model's action limit by 1 (to a maximum of 3). When this model ends its activation, remove this token. Canceled by Slow.",
  'Flicker': "During the end phase, kill this model. This token cannot be removed.",
  'Focused': "Before performing a duel, this model may remove this token to receive a + to the duel. Canceled by Distracted.",
  'Fragile Ego': "After another enemy model is chosen to activate, if this model has not activated this turn, the crew that applied this token may remove it to force this model to activate instead.",
  'Fright': "This model considers its 🛡️ abilities blank. After a friendly model succeeds in a ✨ action targeting this model, it may choose to receive one additional raise; if it does, remove this token after resolving the action.",
  'Frozen Solid': "This model may not be moved by enemy effects. After either this model suffers damage or an enemy model targets this model with the Interact action, remove this token (this model may target itself with the Interact action).",
  'Glowy': "Attacks that target this model are unaffected by concealing terrain. During the end phase, remove this token.",
  'Glutted': "When this model ends its activation, it may remove this token to heal 1.",
  'Graft': "During the end phase, this model may remove this token to heal 2.",
  'Greedy': "When this model would discard an upgrade, it may instead remove this token.",
  'Hastened': "This model receives +2 Sp. When this model ends its activation, remove this token. Canceled by Staggered.",
  'Hidden': "This model gains cover. During the end phase, remove this token. Canceled by Exposed.",
  'Hunger': "When this model ends its activation, it must deal 1 damage to another of its allies within 1\" to remove this token, or deal 1 damage to itself.",
  'Impact': "When this model succeeds in an attack action that deals damage, it must remove this token to deal +1 damage.",
  'Improvised Part': "This model may declare tactical actions printed on the stat cards of non-master allies within 6\" as if they were printed on this model's stat card. After declaring such an action, remove this token.",
  'Incurable': "This model cannot heal. During the end phase, remove this token.",
  'Injured': "This model suffers -1 to its Df and Wp. During the end phase, remove this token. Canceled by Bolstered.",
  'Insight': "Before performing a duel, this model may remove this token to look at the top card of its fate deck and may discard it.",
  'Instinct': "When this model succeeds in an attack action, it may remove this token to receive an additional raise.",
  'Interesting Parts': "This model is affected by the enemy crew card as if it were a unique model allied to the enemy leader, but it may not affect or use power bars. This model considers enemy non-Scheme, non-Strategy markers to be friendly.",
  'Life': "When this model suffers damage, it may remove this token. If it does so, it may not be reduced to below 1 health.",
  'New Blood': "This model gains the Family keyword.",
  'Numb': "This model loses its Don't Turn Your Back ability (if any) and does not prevent friendly models from declaring the Interact action due to:\n■ Being engaged with this model.\n■ This model being in base contact with a marker.\n■ Leaving this model's engagement range. During the end phase, remove this token.",
  'Paranoia': "When this token is removed, the crew that applied it may move this model up to 4\" and then make a Scheme marker into base contact with it, after resolving the current action (if any). During the end phase, this model must either discard a card or remove this token.",
  'Parasite': "When this model is killed, the crew that applied this token infuses a 💎.",
  'Perforated': "After this model resolves the Walk or Charge action, deal 1 damage to it per inch it moved (to a maximum of 3). Other models may target this model with the Interact action to remove this token.",
  'Poison': "During the end phase deal 1 irreducible damage to this model.",
  'Promoted': "If this model is non-unique it receives +1 Skl when declaring attack actions.",
  'Reload': "When a model in this model's LoS ends its activation, this model may remove this token to declare a 🔫 targeting that model. If it does so, no other models in this crew may use a Reload token until the next model activates.",
  'Replica': "After this model discards an upgrade, it may remove this token to attach the discarded upgrade.",
  'Shame': "This model cannot be targeted by the actions of other enemy models. When this model ends its activation, it may choose to deal 1 damage to itself to remove this token.",
  'Shielded': "When this model is dealt non-irreducible damage, it must remove this token to reduce that damage by 1. This token may reduce damage to 0.",
  'Sin': "This model must deal 1 irreducible damage to an enemy model within 6\" to declare non-general actions. When this model ends its activation, remove this token.",
  'Slow': "Reduce this model's action limit by 1 (to a minimum of 1). When this model ends its activation, remove this token. Canceled by Fast.",
  'Spiritual Chains': "When this model flips, cheats, or discards the black joker, it is dealt 2 damage and then this token is removed.",
  'Staggered': "This model suffers -2 Sp and cannot be moved by other enemy models. When this model ends its activation, remove this token. Canceled by Hastened.",
  'Stunned': "This model cannot declare triggers and it counts all ⚡ symbols on its card as blank. When this model ends its activation, remove this token.",
  'Summon': "This model cannot declare the Interact action. This model does not infuse a 💎 for its crew when it is killed. This token cannot be removed.",
  'Suppressed': "When this model declares a ✨ action, it must drain a 💎 or the action fails. After this model resolves a ✨ action, remove this token.",
  'Voyage': "When this model would be moved by an enemy effect, it may remove this token. If it does so, this model controls the move.",
}

interface Props {
  card: CrewCardData
  onChange: (card: CrewCardData) => void
}

export default function CrewCardForm({ card, onChange }: Props) {
  const update = (patch: Partial<CrewCardData>) => onChange({ ...card, ...patch })

  // — Ability group helpers —
  const updateAbilityGroup = (groupId: string, patch: Partial<AbilityGroup>) =>
    update({ abilityGroups: card.abilityGroups.map(g => g.id === groupId ? { ...g, ...patch } : g) })

  const addAbilityGroup = () => {
    const g: AbilityGroup = { id: crypto.randomUUID(), uniqueOnly: false, excludePeon: false, excludeSummonToken: false, abilities: [] }
    update({ abilityGroups: [...card.abilityGroups, g] })
  }

  const removeAbilityGroup = (groupId: string) =>
    update({ abilityGroups: card.abilityGroups.filter(g => g.id !== groupId) })

  const addAbility = (groupId: string) => {
    const ab: Ability = { id: crypto.randomUUID(), name: '', text: '' }
    const g = card.abilityGroups.find(g => g.id === groupId)!
    updateAbilityGroup(groupId, { abilities: [...g.abilities, ab] })
  }

  const updateAbility = (groupId: string, abilityId: string, patch: Partial<Ability>) => {
    const g = card.abilityGroups.find(g => g.id === groupId)!
    updateAbilityGroup(groupId, { abilities: g.abilities.map(a => a.id === abilityId ? { ...a, ...patch } : a) })
  }

  const removeAbility = (groupId: string, abilityId: string) => {
    const g = card.abilityGroups.find(g => g.id === groupId)!
    updateAbilityGroup(groupId, { abilities: g.abilities.filter(a => a.id !== abilityId) })
  }

  // — Action group helpers —
  const updateActionGroup = (groupId: string, patch: Partial<ActionGroup>) =>
    update({ actionGroups: card.actionGroups.map(g => g.id === groupId ? { ...g, ...patch } : g) })

  const addActionGroup = () => {
    const g: ActionGroup = { id: crypto.randomUUID(), uniqueOnly: false, excludePeon: false, excludeSummonToken: false, actions: [] }
    update({ actionGroups: [...card.actionGroups, g] })
  }

  const removeActionGroup = (groupId: string) =>
    update({ actionGroups: card.actionGroups.filter(g => g.id !== groupId) })

  const addAction = (groupId: string, type: ActionType) => {
    const a: Action = {
      id: crypto.randomUUID(), type, signature: false, name: '',
      rg: '-', skl: '-', rst: type === 'Attack' ? 'Df' : '-', tn: '-', dmg: '-',
      requirement: '', effect: '', triggers: [],
    }
    const g = card.actionGroups.find(g => g.id === groupId)!
    updateActionGroup(groupId, { actions: [...g.actions, a] })
  }

  const updateAction = (groupId: string, actionId: string, patch: Partial<Action>) => {
    const g = card.actionGroups.find(g => g.id === groupId)!
    updateActionGroup(groupId, { actions: g.actions.map(a => a.id === actionId ? { ...a, ...patch } : a) })
  }

  const removeAction = (groupId: string, actionId: string) => {
    const g = card.actionGroups.find(g => g.id === groupId)!
    updateActionGroup(groupId, { actions: g.actions.filter(a => a.id !== actionId) })
  }

  // — Trigger group helpers —
  const updateTriggerGroup = (groupId: string, patch: Partial<TriggerGroup>) =>
    update({ triggerGroups: card.triggerGroups.map(g => g.id === groupId ? { ...g, ...patch } : g) })

  const addTriggerGroup = () => {
    const g: TriggerGroup = {
      id: crypto.randomUUID(),
      uniqueOnly: false,
      excludePeon: false,
      excludeSummonToken: false,
      actionType: 'attack',
      printedOnStatCard: false,
      trigger: { id: crypto.randomUUID(), suit: '🐏', name: '', requirement: '', effect: '' },
    }
    update({ triggerGroups: [...card.triggerGroups, g] })
  }

  const removeTriggerGroup = (groupId: string) =>
    update({ triggerGroups: card.triggerGroups.filter(g => g.id !== groupId) })

  const updateGroupTrigger = (groupId: string, patch: Partial<Trigger>) =>
    update({ triggerGroups: card.triggerGroups.map(g => g.id === groupId ? { ...g, trigger: { ...g.trigger, ...patch } } : g) })

  // — Marker helpers —
  const addMarker = () => {
    const m: Marker = { id: crypto.randomUUID(), name: '', size: '30mm', terrainFeatures: [], effect: '' }
    update({ markers: [...card.markers, m] })
  }

  const updateMarker = (markerId: string, patch: Partial<Marker>) =>
    update({ markers: card.markers.map(m => m.id === markerId ? { ...m, ...patch } : m) })

  const removeMarker = (markerId: string) =>
    update({ markers: card.markers.filter(m => m.id !== markerId) })

  const addTerrainFeature = (markerId: string) => {
    const tf: TerrainFeature = { id: crypto.randomUUID(), feature: '' }
    const m = card.markers.find(m => m.id === markerId)!
    updateMarker(markerId, { terrainFeatures: [...m.terrainFeatures, tf] })
  }

  const updateTerrainFeature = (markerId: string, tfId: string, feature: string) => {
    const m = card.markers.find(m => m.id === markerId)!
    updateMarker(markerId, { terrainFeatures: m.terrainFeatures.map(tf => tf.id === tfId ? { ...tf, feature } : tf) })
  }

  const removeTerrainFeature = (markerId: string, tfId: string) => {
    const m = card.markers.find(m => m.id === markerId)!
    updateMarker(markerId, { terrainFeatures: m.terrainFeatures.filter(tf => tf.id !== tfId) })
  }

  // — Token helpers —
  const addToken = () => {
    const t: Token = { id: crypto.randomUUID(), name: '', effect: '' }
    update({ tokens: [...card.tokens, t] })
  }

  const updateToken = (tokenId: string, patch: Partial<Token>) =>
    update({ tokens: card.tokens.map(t => t.id === tokenId ? { ...t, ...patch } : t) })

  const removeToken = (tokenId: string) =>
    update({ tokens: card.tokens.filter(t => t.id !== tokenId) })

  const handleTokenNameChange = (tokenId: string, name: string) => {
    const token = card.tokens.find(t => t.id === tokenId)!
    const preset = TOKEN_PRESETS[name]
    const effect = preset && !token.effect ? preset : token.effect
    updateToken(tokenId, { name, effect })
  }

  return (
    <form onSubmit={e => e.preventDefault()} className="card-form">

      <section>
        <h3>Basic Info</h3>
        <label>Faction
          <select value={card.faction} onChange={e => update({ faction: e.target.value })}>
            <option value="">(none)</option>
            {FACTIONS.map(f => <option key={f.name} value={f.name}>{f.name}</option>)}
          </select>
        </label>
        <label>Name
          <input value={card.name} onChange={e => update({ name: e.target.value })} placeholder="CREW NAME" />
        </label>
        <label>Master
          <input value={card.master} onChange={e => update({ master: e.target.value })} placeholder="Master Name, Title" />
        </label>
        <label>Keyword
          <input value={card.keyword} onChange={e => update({ keyword: e.target.value })} placeholder="e.g. Nightmare" />
        </label>
      </section>

      <section>
        <h3>Image</h3>
        <label>URL
          <input value={card.imageUrl} onChange={e => update({ imageUrl: e.target.value })} placeholder="https://..." />
        </label>
      </section>

      <section>
        <h3>Crew Ability</h3>
        <textarea
          value={card.crewAbility}
          onChange={e => update({ crewAbility: e.target.value })}
          placeholder="e.g. During the start phase of turn 1..."
          rows={3}
        />
      </section>

      <section>
        <h3>Ability Groups</h3>
        {card.abilityGroups.map((group, gi) => (
          <div key={group.id} className="action-entry">
            <GroupHeader index={gi}
              uniqueOnly={group.uniqueOnly} excludePeon={group.excludePeon} excludeSummonToken={group.excludeSummonToken}
              onChange={patch => updateAbilityGroup(group.id, patch)}
              onRemove={() => removeAbilityGroup(group.id)}
            />
            <div className="subsection">
              {group.abilities.map((ab, i) => (
                <AbilityEntry key={ab.id} ability={ab} index={i}
                  onChange={patch => updateAbility(group.id, ab.id, patch)}
                  onRemove={() => removeAbility(group.id, ab.id)}
                />
              ))}
              <button type="button" onClick={() => addAbility(group.id)}>+ Add Ability</button>
            </div>
          </div>
        ))}
        <button type="button" onClick={addAbilityGroup}>+ Add Ability Group</button>
      </section>

      <section>
        <h3>Trigger Groups</h3>
        {card.triggerGroups.map((group, gi) => (
          <div key={group.id} className="action-entry">
            <GroupHeader index={gi}
              uniqueOnly={group.uniqueOnly} excludePeon={group.excludePeon} excludeSummonToken={group.excludeSummonToken}
              onChange={patch => updateTriggerGroup(group.id, patch)}
              onRemove={() => removeTriggerGroup(group.id)}
            />
            <label>Action type
              <select value={group.actionType} onChange={e => updateTriggerGroup(group.id, { actionType: e.target.value as TriggerActionType })}>
                <option value="attack">all attack actions</option>
                <option value="all">all actions</option>
                <option value="🔫">their 🔫 actions</option>
                <option value="✨">their ✨ actions</option>
                <option value="🗡️">their 🗡️ actions</option>
              </select>
            </label>
            <label className="inline">
              <input type="checkbox" checked={group.printedOnStatCard}
                onChange={e => updateTriggerGroup(group.id, { printedOnStatCard: e.target.checked })} />
              Printed on their stat card
            </label>
            <div className="subsection">
              <p className="label-text">Trigger</p>
              <TriggerEntry trigger={group.trigger} onChange={patch => updateGroupTrigger(group.id, patch)} />
            </div>
          </div>
        ))}
        <button type="button" onClick={addTriggerGroup}>+ Add Trigger Group</button>
      </section>

      <section>
        <h3>Action Groups</h3>
        {card.actionGroups.map((group, gi) => (
          <div key={group.id} className="action-entry">
            <GroupHeader index={gi}
              uniqueOnly={group.uniqueOnly} excludePeon={group.excludePeon} excludeSummonToken={group.excludeSummonToken}
              onChange={patch => updateActionGroup(group.id, patch)}
              onRemove={() => removeActionGroup(group.id)}
            />
            <div className="subsection">
              {group.actions.map(action => (
                <ActionEntry key={action.id} action={action}
                  onChange={patch => updateAction(group.id, action.id, patch)}
                  onRemove={() => removeAction(group.id, action.id)}
                />
              ))}
              <div className="row gap-sm">
                <button type="button" onClick={() => addAction(group.id, 'Attack')}>+ Attack Action</button>
                <button type="button" onClick={() => addAction(group.id, 'Tactical')}>+ Tactical Action</button>
              </div>
            </div>
          </div>
        ))}
        <button type="button" onClick={addActionGroup}>+ Add Action Group</button>
      </section>

      <section>
        <h3>Markers</h3>
        {card.markers.map((marker, i) => (
          <div key={marker.id} className="action-entry">
            <div className="row gap-sm">
              <span className="label-text">{i + 1}.</span>
              <button type="button" onClick={() => removeMarker(marker.id)}>× Remove</button>
            </div>
            <label>Name
              <input value={marker.name} onChange={e => updateMarker(marker.id, { name: e.target.value })} placeholder="Marker name" />
            </label>
            <label>Size
              <select value={marker.size} onChange={e => updateMarker(marker.id, { size: e.target.value as Marker['size'] })}>
                <option value="30mm">30mm (not stated)</option>
                <option value="40mm">40mm</option>
                <option value="50mm">50mm</option>
              </select>
            </label>
            <div className="subsection">
              <p className="label-text">Terrain Features</p>
              {marker.terrainFeatures.map(tf => (
                <div key={tf.id} className="row gap-sm">
                  <input value={tf.feature} onChange={e => updateTerrainFeature(marker.id, tf.id, e.target.value)} placeholder="e.g. hazardous (Fright)" />
                  <button type="button" onClick={() => removeTerrainFeature(marker.id, tf.id)}>×</button>
                </div>
              ))}
              <button type="button" onClick={() => addTerrainFeature(marker.id)}>+ Add Feature</button>
            </div>
            <label>Effect
              <textarea value={marker.effect} onChange={e => updateMarker(marker.id, { effect: e.target.value })} rows={2} placeholder="Effect text (optional)" />
            </label>
          </div>
        ))}
        <button type="button" onClick={addMarker}>+ Add Marker</button>
      </section>

      <section>
        <h3>Tokens</h3>
        {card.tokens.map((token, i) => (
          <div key={token.id} className="action-entry">
            <div className="row gap-sm">
              <span className="label-text">{i + 1}.</span>
              <button type="button" onClick={() => removeToken(token.id)}>× Remove</button>
            </div>
            <label>Name
              <input value={token.name} onChange={e => handleTokenNameChange(token.id, e.target.value)} placeholder="Token name" />
            </label>
            <label>Effect
              <textarea value={token.effect} onChange={e => updateToken(token.id, { effect: e.target.value })} rows={3} placeholder="Effect text" />
            </label>
          </div>
        ))}
        <button type="button" onClick={addToken}>+ Add Token</button>
      </section>

    </form>
  )
}
